# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

stages:
  - build
  - lint
  - format

variables:
  CCACHE_DIR: $CI_PROJECT_DIR/.cache/ccache

.ccache:
  cache:
    key: ccache-$CI_JOB_IMAGE
    paths:
      - $CCACHE_DIR/
    when: always

.python-venv:
  cache:
    - key: pip-cache
      paths:
        - $PIP_CACHE_DIR/
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip

.python-3.11:
  image: tollerort.desy.de/hub.docker.com/python:3.11

.cnstln-ci-img:
  image: gitlab.desy.de:5555/constellation/constellation/constellation_ci:latest

# build stage

build-cpp:
  extends:
    - .ccache
    - .cnstln-ci-img
  stage: build
  script:
    - meson setup build
    - meson compile -C build ${NINJA_OPTIONS}
  artifacts:
    paths:
      - build
    expire_in: 24 hour

# lint stage

.lint:
  stage: lint
  needs: []

lint:clang-tidy:
  extends:
    - .lint
    - .cnstln-ci-img
  needs:
    - job: build-cpp
      artifacts: true
  script:
    - ninja -C build clang-tidy

# format stage

.format:
  stage: format
  needs: []

format:clang-format:
  extends:
    - .format
    - .cnstln-ci-img
  script:
    - meson setup build
    - ninja -C build clang-format-check

format:reuse:
  extends: .format
  image: tollerort.desy.de/hub.docker.com/fsfe/reuse:latest
  script:
    - reuse lint

format:codespell:
  extends:
    - .format
    - .python-venv
    - .python-3.11
  script:
    - pip install codespell
    - codespell
