# SPDX-FileCopyrightText: 2025 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

name: Constellation GitHub CI Pipeline

on:
  push:
    branches: ["**"]
  pull_request:

env:
  CCACHE_DIR: ${{ github.workspace }}/.cache/ccache

jobs:
  build-cpp:
    name: Build C++
    runs-on: ubuntu-latest
    container:
      image: gitlab.desy.de:5555/constellation/constellation/constellation_ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Build with meson
        run: |
          meson setup build
          meson compile -C build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  lint-clang-tidy:
    name: Lint with clang-tidy
    runs-on: ubuntu-latest
    needs: build-cpp
    container:
      image: gitlab.desy.de:5555/constellation/constellation/constellation_ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run clang-tidy
        run: ninja -C build clang-tidy

  format-clang-format:
    name: Check formatting
    runs-on: ubuntu-latest
    container:
      image: gitlab.desy.de:5555/constellation/constellation/constellation_ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format
        run: |
          meson setup build
          ninja -C build clang-format-check

  format-reuse:
    name: Run reuse check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  format-codespell:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Codespell Check
        uses: codespell-project/actions-codespell@v2
